### ISSUE TITLE
Please update (or remove) yarn.lock

### ISSUE THREAD

**Issue by SonarSoftware** [SonarSoftwareInc/customer_portal#28]
There are security vulns that need updating that are referenced in yarn.lock. If we're not using yarn on this project, let's get rid of it. If it is being used, it needs updating.

**Comment by zulandar** [comment]
Resolved in PR #29

**Comment by SonarSoftware** [comment]
This issue actually exists in package.json too, is that used? Axios is referenced in there and needs updating.

**Comment by zulandar** [comment]
PR #30 submitted to remove the package.json and upgrade packages within composer.
