### ISSUE TITLE
Unable to edit the Role form field on the My Details page of the customer portal

### ISSUE THREAD

**Issue by matbram** [SonarSoftwareInc/customer_portal#34]
When viewing the My Details page of the customer portal, you're unable to edit the Role form field.

**Comment by zulandar** [comment]
@SonarSoftware is this something we want to enable within the v2 portal? I believe in the v1 customer portal its not shown or editable from the customer standpoint.

**Comment by zulandar** [comment]
Confirmed role to be removed.
