### ISSUE TITLE
Ticketing 500 error

### ISSUE THREAD

**Issue by gmcintire** [SonarSoftwareInc/customer_portal#4]
Steps to reproduce:

1) Create a new ticket from within customer portal.
2) In sonar instance delete new ticket that was created.
3) In portal ticket still shows 'Waiting for response', and clicking the subject results in 500 error. 

Creating a new ticket afterwords correctly removes previously deleted ticket from Tickets list.

**Comment by SonarSoftware** [comment]
@zulandar This is a caching issue on the portal. I think the best solution is to catch the exception from the not found ticket and force a cache refresh.

**Comment by geneccx** [comment]
Pushed this. It should be live in the next 5 minutes.
