### ISSUE TITLE
Feature Request - Add Pagination to Recent Transactions When Detailed Transactions Are Enabled

### ISSUE THREAD

**Issue by matbram** [SonarSoftwareInc/customer_portal#40]
If the detailed transactions setting is enabled on the settings page for the customer portal and the customer has a lot of transactions, it shows all transactions no matter how far back, causing the page to become very long.

The list of "recent transactions" can become excessively long. This causes problems for customers who need to print invoices /statements, because those now show up under that long list.

Being able to paginate or somehow truncate this a bit would be helpful.

**Comment by SonarSoftware** [comment]
@zulandar You're up buddy

**Comment by zulandar** [comment]
PR #43
