### ISSUE TITLE
Customers Unable to Make Payments Unless They Have a Balance Due

### ISSUE THREAD

**Issue by matbram** [SonarSoftwareInc/customer_portal#41]
Some customers like to pay ahead to make sure their account is always paid up. With the v1 customer portal, you were able to make a payment whether you had a balance due or not.

This looks to be missing from the v2 customer portal and you can only make payments now if there is a due balance instead. 

One workaround I found for this is simply making the url to be: https://portal.example.com/portal/billing/payment

This basically brings up the payments page allowing them to still make a payment, but it's missing from the main billing page where customers can find it unless they owe a balance.

**Comment by SonarSoftware** [comment]
@zulandar Can you take a look at this one too?

**Comment by zulandar** [comment]
Will do

**Comment by zulandar** [comment]
PR #42
