### ISSUE TITLE
Bug: Settings Login 500 error

### ISSUE THREAD

**Issue by Chris2fourlaw** [SonarSoftwareInc/customer_portal#44]
After entering the authentication key, I am presented with this error:

![sonarerror](https://user-images.githubusercontent.com/7269141/62483721-3df07d80-b76d-11e9-893e-26c7fa894f37.PNG)

**Comment by SonarSoftware** [comment]
Hey Chris,

Please reach out to our support team at support@sonar.software and they can help troubleshoot this with you.
