### ISSUE TITLE
Feature Request - HTML Markup for "Login Page Message"

### ISSUE THREAD

**Issue by dcortez** [SonarSoftwareInc/customer_portal#63]
Should be pretty easy to add tinymce to the settings page in order to do HTML Markup for the login page message. Only issue I see is it requires `doctrine/dbal` in order to change the field in the DB to text instead of string. I do have the code pretty much ready for a PR, but wanted to ask about this requirement first.

**Comment by zulandar** [comment]
@dcortez if you have everything written feel free to submit a PR to the master for it and we can review the code before general release.

**Comment by dcortez** [comment]
PR #64

**Comment by zulandar** [comment]
@dcortez This has been pushed out to production
