### ISSUE TITLE
Exit Stopping install.sh from completing

### ISSUE THREAD

**Issue by robertp221** [SonarSoftwareInc/customer_portal#69]
Line 55 in install.sh has "exit" which is stopping the script form working.

https://github.com/SonarSoftwareInc/customer_portal/blob/189af46ccc168cfc36a98a01f99de428e869097b/install.sh#L55

**Comment by zulandar** [comment]
PR #70 opened to resolve this issue.

**Comment by zulandar** [comment]
@robertp221 resolved. Let us know if you have any additional issues or questions.
