### ISSUE TITLE
Unable to rerun install script

### ISSUE THREAD

**Issue by chacken** [SonarSoftwareInc/customer_portal#71]
FYI, it's impossible to rerun the installation script without rebuilding the entire VM/server.

Starting customer_portal_certbot_1 ...
Starting customer_portal_watchtower_1 ... done
Starting customer_portal_redis_1      ... done
Recreating sonar-customerportal       ... error
Starting customer_portal_certbot_1    ... done
ERROR: for sonar-customerportal  Cannot create container for service app: invalid volume specification: '14e49784229073da03b522ea1bec0b0616b18adf3e579085ef6f015de4f8b14e:[/var/www/html/storage]:rw': invalid mount config for type "volume": invalid mount path: '[/var/www/html/storage]' mount path must be absolute

ERROR: for app  Cannot create container for service app: invalid volume specification: '14e49784229073da03b522ea1bec0b0616b18adf3e579085ef6f015de4f8b14e:[/var/www/html/storage]:rw': invalid mount config for type "volume": invalid mount path: '[/var/www/html/storage]' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
root@sonar-portal:~/customer_portal#

**Comment by zulandar** [comment]
@chacken if you run `docker-compose down -v` and then rerun the install script it should work for you.

**Comment by chacken** [comment]
I tried that prior to posting this and it didn't work.

**Comment by zulandar** [comment]
Okay, can you attempt this steps;

`docker-compose down -v`
`docker system prune`

`docker volume ls`
Check to see if you see customerportal_storage anywhere. If so perform `docker volume rm customerportal_storage`

Then kick off the install script.
